services:
  odoo:
    image: odoo:18.0
    env_file: .env
    user: "1000:1000"
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - ./volumes/odoo:/var/lib/odoo
      - ./volumes/odoo/extra-addons:/mnt/extra-addons
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
